In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
total_acc_x = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","Inertial Signals","total_acc_x_train.txt"),delim_whitespace=True,header=None)
total_acc_y = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","Inertial Signals","total_acc_y_train.txt"),delim_whitespace=True,header=None)
total_acc_z = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","Inertial Signals","total_acc_z_train.txt"),delim_whitespace=True,header=None)

/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/3527986001.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  total_acc_x = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","Inertial Signals","total_acc_x_train.txt"),delim_whitespace=True,header=None)
/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/3527986001.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  total_acc_y = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","Inertial Signals","total_acc_y_train.txt"),delim_whitespace=True,header=None)
/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/3527986001.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  total_acc_z = pd.read_cs

In [44]:
total_acc_x[63]

0       1.015292
1       1.021171
2       1.017849
3       1.022019
4       1.020735
          ...   
7347    1.326312
7348    0.769958
7349    0.867896
7350    0.776768
7351    0.719353
Name: 63, Length: 7352, dtype: float64

In [5]:
total_acc_y

0         1         2         3         4         5         6    \
0    -0.123217 -0.126876 -0.124004 -0.124928 -0.125767 -0.124462 -0.127361   
1    -0.123976 -0.126808 -0.127786 -0.126655 -0.123634 -0.124919 -0.124300   
2    -0.120016 -0.121499 -0.122841 -0.123717 -0.123817 -0.121304 -0.121258   
3    -0.133404 -0.134364 -0.135203 -0.134048 -0.130632 -0.123746 -0.118772   
4    -0.128731 -0.127846 -0.128230 -0.129854 -0.132752 -0.133991 -0.131159   
...        ...       ...       ...       ...       ...       ...       ...   
7347 -0.235153 -0.476513 -0.590540 -0.406639 -0.284521 -0.382782 -0.439178   
7348 -0.563117 -0.457915 -0.321938 -0.435739 -0.481027 -0.382705 -0.397017   
7349 -0.171183 -0.199937 -0.231946 -0.219816 -0.187882 -0.185327 -0.201995   
7350 -0.223801 -0.221041 -0.183992 -0.102619 -0.037725 -0.042194 -0.120232   
7351 -0.306051 -0.266605 -0.205361 -0.146666 -0.120943 -0.107600 -0.125513   

           7         8         9    ...       118       119       120  \
0    -0.127891 -0.125868 -0.124368  ... -0.123493 -0.121995 -0.123910   
1    -0.119798 -0.119222 -0.120174  ... -0.117672 -0.119885 -0.122055   
2    -0.125411 -0.129458 -0.129856  ... -0.134438 -0.133090 -0.134369   
3    -0.122888 -0.127193 -0.126323  ... -0.127894 -0.127629 -0.129888   
4    -0.129970 -0.131889 -0.133298  ... -0.121851 -0.122087 -0.123337   
...        ...       ...       ...  ...       ...       ...       ...   
7347 -0.404961 -0.474050 -0.549860  ... -0.361512 -0.323089 -0.292112   
7348 -0.452216 -0.530228 -0.566649  ... -0.195721 -0.202487 -0.204188   
7349 -0.299549 -0.489437 -0.614344  ... -0.211466 -0.323370 -0.301849   
7350 -0.281115 -0.455733 -0.456001  ... -0.291629 -0.269784 -0.228163   
7351 -0.259340 -0.484792 -0.571948  ... -0.417542 -0.438114 -0.459893   

           121       122       123       124       125       126       127  
0    -0.127970 -0.128295 -0.127010 -0.126185 -0.124070 -0.122745 -0.121326  
1    -0.122978 -0.122969 -0.127339 -0.132329 -0.129027 -0.126424 -0.130519  
2    -0.133016 -0.130937 -0.130473 -0.130305 -0.130876 -0.131210 -0.130183  
3    -0.130819 -0.128451 -0.126481 -0.127507 -0.131986 -0.134507 -0.133316  
4    -0.124236 -0.127601 -0.126752 -0.124824 -0.124559 -0.121456 -0.123494  
...        ...       ...       ...       ...       ...       ...       ...  
7347 -0.275639 -0.224981 -0.156650 -0.130634 -0.131772 -0.119933 -0.134762  
7348 -0.165793 -0.129262 -0.153059 -0.205897 -0.269632 -0.297901 -0.257222  
7349 -0.268217 -0.233645 -0.201264 -0.207890 -0.221766 -0.281150 -0.327599  
7350 -0.167212 -0.139224 -0.158709 -0.154120 -0.162009 -0.202037 -0.229127  
7351 -0.494916 -0.504993 -0.486260 -0.453405 -0.397775 -0.349247 -0.332372  

[7352 rows x 128 columns]

In [6]:
total_acc_z.shape

(7352, 128)

In [7]:
pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/test","Inertial Signals","total_acc_x_test.txt"),delim_whitespace=True,header=None).shape

/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/3640892747.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/test","Inertial Signals","total_acc_x_test.txt"),delim_whitespace=True,header=None).shape


(2947, 128)

In [8]:
subject_train = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","subject_train.txt"),delim_whitespace=True,header=None)

/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/686121243.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  subject_train = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","subject_train.txt"),delim_whitespace=True,header=None)


In [9]:
subject_test = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/test","subject_test.txt"),delim_whitespace=True,header=None)

/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/1044806897.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  subject_test = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/test","subject_test.txt"),delim_whitespace=True,header=None)


In [10]:
np.unique(subject_test.values)

array([ 2,  4,  9, 10, 12, 13, 18, 20, 24])

In [11]:
subject_train

0
0      1
1      1
2      1
3      1
4      1
...   ..
7347  30
7348  30
7349  30
7350  30
7351  30

[7352 rows x 1 columns]

In [12]:
y = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","y_train.txt"),delim_whitespace=True,header=None)

/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/311365396.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  y = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","y_train.txt"),delim_whitespace=True,header=None)


In [13]:
y

0
0     5
1     5
2     5
3     5
4     5
...  ..
7347  2
7348  2
7349  2
7350  2
7351  2

[7352 rows x 1 columns]

In [14]:
ACTIVITIES = {
    1: 'WALKING'            ,
    2: 'WALKING_UPSTAIRS'   ,
    3: 'WALKING_DOWNSTAIRS' ,
    4: 'SITTING'            ,
    5: 'STANDING'           ,
    6: 'LAYING'             ,
}

In [15]:
np.unique(subject_train.values)

array([ 1,  3,  5,  6,  7,  8, 11, 14, 15, 16, 17, 19, 21, 22, 23, 25, 26,
       27, 28, 29, 30])

In [16]:
np.where(subject_train.iloc[:,0] == 1)[0]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [40]:
for subject in np.unique(subject_train.values):

    sub_idxs = np.where(subject_train.iloc[:,0] == subject)[0] # this line gives indexes for the particular subject datapoint
    labels = y.loc[sub_idxs] # finds label corresponding to that datapoint
    # print(np.unique(labels.values)[3])
    # Toggle through all the labels.
    for label in np.unique(labels.values):

        # make the folder directory if it does not exist
        # if not os.path.exists(os.path.join("Combined","Train",ACTIVITIES[label])):
        #     os.makedirs(os.path.join("Combined","Train",ACTIVITIES[label]))

        label_idxs = labels[labels.iloc[:,0] == label].index
        accx = []
        accy = []
        accz = []
        print(label_idxs.shape)
        for idx in label_idxs:
            if accx is not None:
                accx = np.hstack((accx,total_acc_x.loc[idx][64:]))
                accy = np.hstack((accy,total_acc_y.loc[idx][64:]))
                accz = np.hstack((accz,total_acc_z.loc[idx][64:]))

        #     else:
        #         accx = total_acc_x.loc[idx]
        #         accy = total_acc_y.loc[idx]
        #         accz = total_acc_z.loc[idx]

        # # saving the data into csv file
        # data = pd.DataFrame({'accx':accx,'accy':accy,'accz':accz})
        # save_path = os.path.join("Combined","Train",ACTIVITIES[label],f"Subject_{subject}.csv")
        # data.to_csv(save_path,index=False)

(95,)
(53,)
(49,)
(47,)
(53,)
(50,)
(58,)
(59,)
(49,)
(52,)
(61,)
(62,)
(56,)
(47,)
(47,)
(44,)
(56,)
(52,)
(57,)
(51,)
(48,)
(55,)
(57,)
(57,)
(57,)
(51,)
(47,)
(48,)
(53,)
(52,)
(48,)
(41,)
(38,)
(46,)
(54,)
(54,)
(59,)
(54,)
(46,)
(53,)
(47,)
(57,)
(59,)
(54,)
(45,)
(54,)
(60,)
(51,)
(54,)
(48,)
(42,)
(59,)
(53,)
(72,)
(51,)
(51,)
(47,)
(69,)
(78,)
(70,)
(61,)
(48,)
(46,)
(64,)
(78,)
(71,)
(52,)
(40,)
(39,)
(73,)
(73,)
(83,)
(52,)
(47,)
(45,)
(85,)
(89,)
(90,)
(46,)
(42,)
(36,)
(62,)
(63,)
(72,)
(59,)
(51,)
(54,)
(68,)
(68,)
(72,)
(74,)
(65,)
(58,)
(65,)
(74,)
(73,)
(59,)
(55,)
(50,)
(78,)
(74,)
(76,)
(57,)
(51,)
(44,)
(70,)
(80,)
(74,)
(54,)
(51,)
(46,)
(72,)
(79,)
(80,)
(53,)
(49,)
(48,)
(60,)
(65,)
(69,)
(65,)
(65,)
(62,)
(62,)
(59,)
(70,)


64     1.426164
65     1.496596
66     1.305815
67     0.973824
68     0.691378
         ...   
123    0.876499
124    0.579224
125    0.713040
126    0.990639
127    1.094669
Name: 78, Length: 64, dtype: float64

In [38]:
ax=np.hstack((total_acc_x.loc[78][64:],total_acc_x.loc[79][64:]))

In [39]:
np.hstack((ax,total_acc_x.loc[80][64:])).shape

(192,)

In [19]:
x_train = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","x_train.txt"),delim_whitespace=True,header=None)

/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/2448897879.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  x_train = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train","x_train.txt"),delim_whitespace=True,header=None)


In [45]:
x_train

0         1         2         3         4         5         6    \
0     0.288585 -0.020294 -0.132905 -0.995279 -0.983111 -0.913526 -0.995112   
1     0.278419 -0.016411 -0.123520 -0.998245 -0.975300 -0.960322 -0.998807   
2     0.279653 -0.019467 -0.113462 -0.995380 -0.967187 -0.978944 -0.996520   
3     0.279174 -0.026201 -0.123283 -0.996091 -0.983403 -0.990675 -0.997099   
4     0.276629 -0.016570 -0.115362 -0.998139 -0.980817 -0.990482 -0.998321   
...        ...       ...       ...       ...       ...       ...       ...   
7347  0.299665 -0.057193 -0.181233 -0.195387  0.039905  0.077078 -0.282301   
7348  0.273853 -0.007749 -0.147468 -0.235309  0.004816  0.059280 -0.322552   
7349  0.273387 -0.017011 -0.045022 -0.218218 -0.103822  0.274533 -0.304515   
7350  0.289654 -0.018843 -0.158281 -0.219139 -0.111412  0.268893 -0.310487   
7351  0.351503 -0.012423 -0.203867 -0.269270 -0.087212  0.177404 -0.377404   

           7         8         9    ...       551       552       553  \
0    -0.983185 -0.923527 -0.934724  ... -0.074323 -0.298676 -0.710304   
1    -0.974914 -0.957686 -0.943068  ...  0.158075 -0.595051 -0.861499   
2    -0.963668 -0.977469 -0.938692  ...  0.414503 -0.390748 -0.760104   
3    -0.982750 -0.989302 -0.938692  ...  0.404573 -0.117290 -0.482845   
4    -0.979672 -0.990441 -0.942469  ...  0.087753 -0.351471 -0.699205   
...        ...       ...       ...  ...       ...       ...       ...   
7347  0.043616  0.060410  0.210795  ... -0.070157 -0.588433 -0.880324   
7348 -0.029456  0.080585  0.117440  ...  0.165259 -0.390738 -0.680744   
7349 -0.098913  0.332584  0.043999  ...  0.195034  0.025145 -0.304029   
7350 -0.068200  0.319473  0.101702  ...  0.013865  0.063907 -0.344314   
7351 -0.038678  0.229430  0.269013  ... -0.058402 -0.387052 -0.740738   

           554       555       556       557       558       559       560  
0    -0.112754  0.030400 -0.464761 -0.018446 -0.841247  0.179941 -0.058627  
1     0.053477 -0.007435 -0.732626  0.703511 -0.844788  0.180289 -0.054317  
2    -0.118559  0.177899  0.100699  0.808529 -0.848933  0.180637 -0.049118  
3    -0.036788 -0.012892  0.640011 -0.485366 -0.848649  0.181935 -0.047663  
4     0.123320  0.122542  0.693578 -0.615971 -0.847865  0.185151 -0.043892  
...        ...       ...       ...       ...       ...       ...       ...  
7347 -0.190437  0.829718  0.206972 -0.425619 -0.791883  0.238604  0.049819  
7348  0.064907  0.875679 -0.879033  0.400219 -0.771840  0.252676  0.050053  
7349  0.052806 -0.266724  0.864404  0.701169 -0.779133  0.249145  0.040811  
7350 -0.101360  0.700740  0.936674 -0.589479 -0.785181  0.246432  0.025339  
7351 -0.280088 -0.007739 -0.056088 -0.616956 -0.783267  0.246809  0.036695  

[7352 rows x 561 columns]

In [23]:
x_gyro_train = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train/Inertial Signals","body_acc_x_train.txt"),delim_whitespace=True,header=None)

/var/folders/nx/hp2vpgr15lsfzsnf9zg0ys_c0000gn/T/ipykernel_40508/385601268.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  x_gyro_train = pd.read_csv(os.path.join("../HAR/UCI HAR Dataset/train/Inertial Signals","body_acc_x_train.txt"),delim_whitespace=True,header=None)


In [24]:
x_gyro_train.shape

(7352, 128)

In [47]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import os

# Constants
time = 10
offset = 100
folders = ["LAYING","SITTING","STANDING","WALKING","WALKING_DOWNSTAIRS","WALKING_UPSTAIRS"]
classes = {"WALKING":1,"WALKING_UPSTAIRS":2,"WALKING_DOWNSTAIRS":3,"SITTING":4,"STANDING":5,"LAYING":6}

combined_dir = os.path.join("../Combined")

In [56]:
X_train=[]
y_train=[]
dataset_dir = os.path.join(combined_dir,"Train")

for folder in folders:
    files = os.listdir(os.path.join(dataset_dir,folder))
    for file in files:
        df = pd.read_csv(os.path.join(dataset_dir,folder,file),sep=",",header=0)
        df = df[offset:offset+time*50]
        print(df.values)
#         X_train.append(df.values)
#         y_train.append(classes[folder])

# X_train = np.array(X_train)
# y_train = np.array(y_train)

[[0.06584544 0.4377584  0.9055797 ]
 [0.068501   0.4353286  0.9073059 ]
 [0.07408331 0.4319113  0.9043398 ]
 ...
 [0.06508806 0.4046835  0.9259598 ]
 [0.06507871 0.4037949  0.9212075 ]
 [0.06556786 0.4044061  0.9170962 ]]
[[0.0513123  0.6617173  0.7598277 ]
 [0.05157506 0.6600909  0.7606677 ]
 [0.05132473 0.6593124  0.7662147 ]
 ...
 [0.05391553 0.6692178  0.7549661 ]
 [0.0550801  0.6697168  0.7534285 ]
 [0.05615585 0.6685066  0.7567976 ]]
[[0.253887  0.6446213 0.7305601]
 [0.2547409 0.6470096 0.7330282]
 [0.256914  0.6468081 0.7354798]
 ...
 [0.2489302 0.642803  0.7323693]
 [0.2503708 0.6447095 0.7369245]
 [0.2513104 0.6440663 0.735841 ]]
[[-0.338486  -0.5257631  0.7826314]
 [-0.3486269 -0.5197535  0.7867927]
 [-0.3473831 -0.5056994  0.7933079]
 ...
 [ 0.1286809  0.9977822 -0.1146345]
 [ 0.1283305  0.9902453 -0.1184711]
 [ 0.127832   0.992517  -0.1184475]]
[[ 2.636497e-03  8.359239e-01  5.812873e-01]
 [ 3.130300e-03  8.333563e-01  5.845124e-01]
 [ 2.424003e-03  8.279865e-01  5.857250e